name: Laravel CI

on:
  push:
    branches:
      - main
      - aheebwa
      - lynn
      - V2*
  pull_request:
     types: [assigned, edited, opened, synchronize, reopened]
      


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the latest version of the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up PHP with version 8.2
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      # Install Composer dependencies
      - name: Install Composer dependencies
        run: composer install  --optimize-autoloader --prefer-dist --no-interaction --no-scripts --no-progress


      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
       

      - name: Install NPM Dependencies
        run: npm run build
      
       - name: Build NPM Assets
        run: npm run build


      
      # Generate application key (if necessary)
      - name: Generate Application Key
        run: php artisan key:generate


      - name: Set environment variables
        run: |
          echo "APP_ENV=testing" >> .env
          echo "APP_KEY=base64:XYzqBnlzNzrKtagh9OOSKoAVzgMDE6PlJB25K7vdXMs=" >> .env
          echo "DB_CONNECTION=mysql" >> .env
          echo "DB_DATABASE=database/database.mysql" >> .env

      # Run database migrations (if required)
      - name: Run Migrations
        run: php artisan migrate --force

      - name: Execute tests (Unit and Feature tests) via PHPUnit
       run: vendor/bin/phpunit

      - name: Install PHP_CodeSniffer
        run: composer require --dev squizlabs/php_codesniffer

      - name: Run PHP_CodeBeautifier (phpcbf)
        run: vendor/bin/phpcbf --standard=PSR12 app/ tests/
        continue-on-error: true

      - name: Run PHP_CodeSniffer (phpcs)
        run: vendor/bin/phpcs --standard=PSR12 app/ tests/
        continue-on-error: true

      # Run tests using PHPUnit
      - name: Run Tests
        run: php artisan test
